"""Default bounds for CM profile collection configuration."""

DEFAULT_SINCE_HOURS = 24
DEFAULT_LIMIT = 20
DEFAULT_MIN_DURATION_SEC = 60
DEFAULT_RECENT_LIMIT = 20
DEFAULT_RECENT_SELECT = 5
DEFAULT_RECENT_WINDOW_MINUTES = 60
MAX_RECENT_LIMIT = 100
MAX_RECENT_SELECT = 20
