apiVersion: v1
kind: Service
metadata:
  name: {{ include "query-doctor.fullname" . | quote }}
  labels:
    {{- include "query-doctor.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "query-doctor.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
