"""Curated static Help page for the local Query Doctor web UI."""

from __future__ import annotations

from typing import Any

from query_doctor.web.ui.i18n import normalize_ui_language
from query_doctor.web.ui.pages import render_page


def render_help_page(settings: Any) -> str:
    llm_enabled = not getattr(settings, "no_llm", False)
    language = normalize_ui_language(getattr(settings, "language", "en"))
    return render_page(
        settings,
        active_nav="help",
        show_run_panel=False,
        extra_sections=[render_help_content(llm_enabled=llm_enabled, language=language)],
    )


def render_demo_guide_page(settings: Any) -> str:
    """Legacy /demo alias.

    Demo talk-track content lives in repository docs. The product UI keeps one
    maintained static guide so navigation does not drift from Details behavior.
    """

    return render_help_page(settings)


def render_help_content(*, llm_enabled: bool = True, language: str = "en") -> str:
    if normalize_ui_language(language) == "ru":
        return render_help_content_ru(llm_enabled=llm_enabled)
    actions_label = "Reports and optimizer"
    optimizer_label = "Query LLM optimizer" if llm_enabled else "Query optimizer"
    selected_action_line = (
        "Run <strong>Python Report</strong>, optional <strong>LLM narrative</strong>, or <strong>Query LLM optimizer</strong> only from a selected Details page."
        if llm_enabled
        else "Run <strong>Python Report</strong> or <strong>Query optimizer</strong> only from a selected Details page."
    )
    web_scan_boundary = (
        "Web scans do not auto-run reports, LLM narratives, or optimizer drafts."
        if llm_enabled
        else "Web scans do not auto-run reports or optimizer jobs."
    )
    known_query_boundary = (
        "It collects and analyzes one query without automatic LLM execution, clears the input after submit, and appends the result to the Known Query ID analysis table."
        if llm_enabled
        else "It collects and analyzes one query without automatic report or optimizer execution, clears the input after submit, and appends the result to the Known Query ID analysis table."
    )
    action_copy = (
        "<p><strong>Reports and optimizer</strong> contains explicit buttons for the recommended Python Report baseline, optional LLM narrative, Query LLM optimizer, and combined Python report + optimizer execution. Outputs are rendered only after deterministic validation. If validation rejects generated output, partial content stays untrusted and hidden.</p>"
        if llm_enabled
        else "<p><strong>Reports and optimizer</strong> contains explicit buttons for Python Report, Query optimizer, and combined report + optimizer execution. Outputs are rendered only after deterministic validation. If validation rejects generated output, partial content stays untrusted and hidden.</p>"
    )
    report_copy = (
        "<p>Analyzer facts are the source of truth. Python Report is the deterministic baseline. The optional LLM narrative owns wording only, writes a separate validated artifact, and raw LLM output is never trusted until validation passes.</p>"
        if llm_enabled
        else "<p>Analyzer facts are the source of truth. In Python-only mode, reports are generated by deterministic Python without LLM calls. Trusted reports default to English, and raw profile text or SQL stays outside trusted output.</p>"
    )
    optimizer_copy = (
        "The details-page optimizer uses server-owned source scope from the analyzed case. Python classifies risk, selects a mode or recipe, may execute a narrow deterministic recipe patch, otherwise asks the LLM to assemble a draft, and then validates read-only scope, table set, filters, joins, projection shape, result shape, and recipe-specific invariants before any SQL draft is trusted."
        if llm_enabled
        else "The details-page optimizer uses server-owned source scope from the analyzed case. Python classifies risk, selects a mode or recipe, may execute a narrow deterministic recipe patch, and then validates read-only scope, table set, filters, joins, projection shape, result shape, and recipe-specific invariants before any SQL draft is trusted."
    )
    auto_report_answer = (
        "To avoid mass LLM execution and trusted-looking output without a selected case. Report generation remains an explicit user action."
        if llm_enabled
        else "To avoid trusted-looking output without a selected case. Report generation remains an explicit user action."
    )
    return f"""
<section class="panel docs-panel help-panel" aria-label="Query Doctor help">
<h1>Help</h1>
<div class="report-body help-body">
<p class="help-lede">Query Doctor is a local-first Big Data query diagnostics tool focused today on Apache Impala production triage for operators. It ranks suspicious Recent queries, collects bounded profile context, derives deterministic evidence, optionally enriches it with safe metadata and runtime context, and generates validated raw-free reports. The implemented production engine is Apache Impala.</p>

<nav class="help-card-grid" aria-label="Help shortcuts">
<a class="help-card" href="/"><span>Diagnose</span><strong>Triage Recent queries or inspect one Known Query ID.</strong></a>
<a class="help-card" href="/#recent-results"><span>Results</span><strong>Read priority filters, findings, metadata, and stats signals.</strong></a>
<a class="help-card" href="#details-actions"><span>Details</span><strong>Start with Recommended changes, then expand evidence.</strong></a>
<a class="help-card" href="/trino/compact-diagnosis"><span>Trino compact</span><strong>Render direct or packaged raw-free boundary JSON, not product support.</strong></a>
<a class="help-card" href="#safety"><span>Safety</span><strong>See what browser output intentionally hides.</strong></a>
</nav>

<h2>On this page</h2>
<ul class="help-toc">
<li><a href="#quick-start">Quick start</a></li>
<li><a href="#workflows">Workflows</a></li>
<li><a href="#results-table">Results table</a></li>
<li><a href="#details-actions">{actions_label}</a></li>
<li><a href="#metadata">Metadata</a></li>
<li><a href="#safety">Safety boundary</a></li>
<li><a href="#github-docs">GitHub documentation</a></li>
<li><a href="#common-questions">Common questions</a></li>
</ul>

<section id="quick-start" class="help-section-block">
<h2>Quick start</h2>
<ol class="help-step-list">
<li><a href="/">Open Diagnose</a> and choose <strong>Finished queries</strong>, <strong>Running now</strong>, or <strong>One Query ID</strong> in the first control.</li>
<li>Use <strong>Finished queries</strong> for normal batch triage. Use <strong>Running now</strong> only when you need a lower-confidence live snapshot.</li>
<li>Switch to <strong>Known Query ID</strong> when you already have one query ID. Recent-query filters are intentionally hidden in that mode.</li>
<li>Open a result row in the same tab and start with <strong>Recommended changes</strong>. Expand <strong>Diagnostics and evidence</strong> when you need pipeline state or analyzer basis.</li>
<li>{selected_action_line}</li>
</ol>
</section>

<div class="help-topic-stack">
<details id="workflows" class="help-topic" open>
<summary><span>Workflows</span><small>Recent queries, Running now, Known Query ID</small></summary>
<div class="help-topic-body">
<p>Most demos and investigations start from <strong>Recent queries</strong>, the flagship production triage workflow. Use <strong>Known Query ID</strong> only when you already have one query ID and want to skip batch discovery.</p>

<h3>Recent queries</h3>
<p>Recent queries is the primary operator workflow. It reads query summaries from the selected source, applies filters, collects bounded profiles for selected queries, runs deterministic analysis, and shows action-oriented result filters. {web_scan_boundary}</p>
<ul>
<li>Verify <strong>Source cluster</strong> first. Credentials and endpoints stay in local config; the browser only selects among configured sources.</li>
<li>The first workflow control selects <strong>Finished queries</strong>, <strong>Running now</strong>, or <strong>One Query ID</strong>. Finished queries remain the default triage path.</li>
<li>For <strong>Finished queries</strong>, choose <strong>Scan date</strong> and <strong>Scan Hour</strong>, leave <strong>Minimum duration</strong> empty to include long queries and repeated short workload patterns, or set it to narrow the scan to longer-running queries.</li>
<li>Owner-gated sources keep the required <strong>Username</strong> visible in Basic scan. Optional user and resource-pool filters stay config-owned unless <code>web_advanced_settings_enabled</code> makes them editable in Advanced settings.</li>
<li>Collection concurrency uses bounded defaults and optional local config keys such as <code>recent_parallelism</code> and <code>recent_metadata_jobs</code>; normal browser scans do not require tuning worker counts.</li>
<li>Runtime context is collected automatically when the selected source supports it. Cloudera Manager clusters add bounded event and metric summaries; direct Impala Recent and Running scans use profile evidence and skip Cloudera Manager-only context.</li>
<li>The Results filter shows all available views in one toolbar: <strong>Needs attention</strong>, <strong>Worth reviewing</strong>, repeated workloads, rewrite opportunities, and stats candidates.</li>
<li><strong>Rewrite opportunities</strong> are deterministic query-shape review opportunities. They do not promise speedup and do not execute SQL.</li>
<li><strong>Stats to check</strong> rows require metadata evidence, estimate mismatch, and planning-sensitive runtime symptoms. They still require EXPLAIN comparison and a comparable rerun.</li>
<li><strong>Only queries with spills</strong> is a display filter over analyzed results; it does not change scan parameters.</li>
</ul>

<h3>Running now</h3>
<p>Running now uses the same result and details shape as Finished queries, but scans only queries that are running at scan time. It has no Scan date or Scan Hour filter. Profiles can be incomplete until a query finishes, so findings can be lower-confidence than completed-query analysis. Runtime context is collected automatically when the selected source supports it.</p>

<h3>Known Query ID</h3>
<p>Known Query ID is for one explicit query ID. Use the shared Cluster selector above What to analyze, then enter the Query ID and run analysis. {known_query_boundary}</p>
</div>
</details>

<details id="results-table" class="help-topic">
<summary><span>Results table</span><small>Filters, columns, and triage wording</small></summary>
<div class="help-topic-body">
<p>The table is a triage surface. Open a row for Details before making production changes.</p>

<h3>Columns and filters</h3>
<ul>
<li>The filter toolbar shows counts for available result views, and a compact scanned-volume note shows how many summaries were inspected.</li>
<li><strong>Scan context</strong> after the table explains coverage, notes, and workload signals for the result set. Critical scan warnings still open above the table.</li>
<li><strong>Rank</strong> is ordering within the current group, not a root-cause verdict.</li>
<li><strong>Query ID</strong> opens the details page for the selected case.</li>
<li><strong>User</strong> shows the sanitized query user when available.</li>
<li><strong>Priority</strong> combines a word label with the deterministic analyzer score.</li>
<li><strong>Duration</strong> comes from query summary data when available.</li>
<li><strong>Table stats</strong> summarizes table or partition statistics availability.</li>
<li><strong>Metadata</strong> summarizes read-only metadata collection status.</li>
<li><strong>Rewrite opportunities</strong> use Finding, Candidate, Impact, Confidence, and Rewrite support columns.</li>
<li><strong>Stats to check</strong> uses Finding, Candidate, Need, Speed benefit, and Confidence columns.</li>
<li>Cases without triage severity and without Medium/High optimization or statistics update candidacy are intentionally hidden from separate result filters.</li>
<li><strong>Finding</strong> explains deterministic signals without raw evidence.</li>
</ul>
</div>
</details>

<details id="details-actions" class="help-topic">
<summary><span>{actions_label}</span><small>Recommended changes, diagnostics, reports, optimizer</small></summary>
<div class="help-topic-body">
<p>Details shows a browser-safe summary for one analyzed query. <strong>Recommended changes</strong> leads with what to change and how to verify it, then shows where to inspect and why deterministic facts support the path. <strong>Diagnostics and evidence</strong> keeps pipeline state, supporting findings, runtime, metadata, runtime metrics, and technical signals available without turning the first screen into a low-level evidence dump.</p>
{action_copy}

<h3>Validated reports</h3>
{report_copy}
<p>The report writer reads deterministic facts, Python-owned report contract digest, case differentiators, and Python-owned recommendation candidates. It must not infer from raw profile text or raw SQL.</p>

<h3>Details-page {optimizer_label}</h3>
<p>{optimizer_copy}</p>
<p>If validation fails, Query Doctor can show trusted recommendations-only or no-rewrite guidance instead of an unsafe draft.</p>
</div>
</details>

<details id="metadata" class="help-topic">
<summary><span>Metadata</span><small>Bounded read-only table facts</small></summary>
<div class="help-topic-body">
<p>Metadata collection is explicit, bounded, read-only, and allowlisted. Metadata can be unavailable or partial; that is a normal degraded state.</p>
<h3>Allowed metadata summaries</h3>
<ul>
<li>Table definition summary</li>
<li>Table statistics summary</li>
<li>Column statistics summary</li>
</ul>
<p>Query Doctor does not run user queries, maintenance statements, metadata cache updates, schema changes, or data-changing statements for metadata collection.</p>
</div>
</details>

<details id="safety" class="help-topic">
<summary><span>Safety boundary</span><small>What browser output shows and hides</small></summary>
<div class="help-topic-body">
<p>Browser UI intentionally hides raw query text, raw profile text, raw metadata output, filesystem locations, case directory details, process output, secrets, environment secret values, runtime internals, and raw evidence links. This is a product boundary, not a missing feature.</p>
<p>Safe browser output means summarized deterministic facts, statuses, validated reports, trusted optimizer outcomes, and bounded limitations.</p>
</div>
</details>

<details id="github-docs" class="help-topic">
<summary><span>GitHub documentation</span><small>Maintained external docs</small></summary>
<div class="help-topic-body">
<p>This page stays short and task-oriented. Full documentation lives in the repository on GitHub:</p>
<ul class="help-link-list">
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/README.md" target="_blank" rel="noopener noreferrer">Project README</a> - install, commands, workflow overview, and current public status.</li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/README.md" target="_blank" rel="noopener noreferrer">Documentation index</a> - the maintained map of current docs.</li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/security-model.md" target="_blank" rel="noopener noreferrer">Security model</a> - public security, privacy, and demo-sharing overview.</li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/safety-contract.md" target="_blank" rel="noopener noreferrer">Safety contract</a> - browser/report trust and redaction rules.</li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/roadmap.md" target="_blank" rel="noopener noreferrer">Roadmap</a> - implemented scope, near-term work, and future seams.</li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/DEMO.md" target="_blank" rel="noopener noreferrer">Synthetic demo docs</a> - maintained demo talk track outside the product UI.</li>
</ul>
</div>
</details>

<details id="common-questions" class="help-topic">
<summary><span>Common questions</span><small>Safety, metadata, reports, and future scope</small></summary>
<div class="help-topic-body">
<h3>Why can I not see the query SQL?</h3>
<p>Raw query text can contain sensitive business logic, table names, and literals. Query Doctor shows safe summaries and deterministic findings instead.</p>
<h3>Why can I not see the full profile?</h3>
<p>Full profiles can be large and sensitive. The UI shows analyzer-owned facts and bounded status summaries.</p>
<h3>Why is metadata partial or skipped?</h3>
<p>Metadata collection is bounded. It can be disabled, unavailable, limited to top cases, or stopped by safety limits. Profile-based findings still remain usable.</p>
<h3>Why does Recent queries not generate reports automatically?</h3>
<p>{auto_report_answer}</p>
<h3>Can Query Doctor execute optimized SQL?</h3>
<p>No. Details-page optimizer actions can produce trusted drafts or recommendations, but Query Doctor never executes generated SQL. Benchmarks must be separate explicit read-only checks outside the UI workflow.</p>
<h3>Does a stats gap mean stats caused the slowdown?</h3>
<p>No. Treat it as a statistics update candidate only when metadata gaps, estimate mismatch, and planning-sensitive runtime symptoms line up. Confirmation requires EXPLAIN comparison and a comparable rerun.</p>
<h3>Does runtime metrics context prove root cause?</h3>
<p>Usually no. Runtime metrics are bounded context. They become stronger only when correlated with deterministic profile evidence.</p>
<h3>Future scope</h3>
<h3>Can Query Doctor support Trino, Spark SQL, StarRocks, Doris, ClickHouse, Dremio, or another Big Data SQL engine?</h3>
<p>Not yet. Future engine work is scoped to actively developed Big Data SQL, MPP analytical, and lakehouse runtimes, not generic OLTP databases. Each engine needs a safe read-only collection contract, metadata allowlist, parser/profile support, browser safety tests, and report validator coverage before it becomes supported behavior.</p>
<h3>Does the storage backend matter?</h3>
<p>Yes, but it is a separate dimension from the query engine. Query Doctor can keep bounded storage-family context such as HDFS or object-store when metadata exposes a safe location scheme. It does not expose table locations or object URIs, and object-store remote reads are not treated as HDFS locality failures. Future table-layout context may support candidates such as small-file risk or planning pressure, but storage context cannot prove root cause by itself.</p>
</div>
</details>
</div>
</section>
""".strip()


def render_help_content_ru(*, llm_enabled: bool = True) -> str:
    actions_label = "Отчеты и оптимизатор"
    optimizer_label = "Query LLM optimizer" if llm_enabled else "Query optimizer"
    selected_action_line = (
        "Запускайте <strong>Python-отчет</strong>, optional <strong>LLM narrative</strong> или <strong>Query LLM optimizer</strong> только со страницы Details выбранного кейса."
        if llm_enabled
        else "Запускайте <strong>Python-отчет</strong> или <strong>Query optimizer</strong> только со страницы Details выбранного кейса."
    )
    web_scan_boundary = (
        "Web-сканы не запускают отчеты, LLM narrative или optimizer drafts автоматически."
        if llm_enabled
        else "Web-сканы не запускают отчеты или optimizer jobs автоматически."
    )
    known_query_boundary = (
        "Он собирает и анализирует один query ID без автоматического LLM-запуска, очищает ввод после submit и добавляет результат в таблицу Known Query ID."
        if llm_enabled
        else "Он собирает и анализирует один query ID без автоматической генерации report или optimizer, очищает ввод после submit и добавляет результат в таблицу Known Query ID."
    )
    action_copy = (
        "<p><strong>Отчеты и оптимизатор</strong> содержит явные кнопки для рекомендуемого Python-отчета, optional LLM narrative, Query LLM optimizer и combined Python report + optimizer execution. Outputs рендерятся только после deterministic validation; rejected или partial output остается hidden.</p>"
        if llm_enabled
        else "<p><strong>Отчеты и оптимизатор</strong> содержит явные кнопки для Python-отчета, Query optimizer и combined report + optimizer execution. Outputs рендерятся только после deterministic validation; rejected или partial output остается hidden.</p>"
    )
    report_copy = (
        "<p>Факты анализатора остаются источником истины. Python-отчет является deterministic baseline. Optional LLM narrative отвечает только за формулировки, пишет отдельный валидированный artifact, и raw LLM output не считается trusted, пока Python validation не примет результат.</p>"
        if llm_enabled
        else "<p>Факты анализатора остаются источником истины. В Python-only режиме reports генерируются детерминированным Python без LLM calls. Raw profile text и SQL не попадают в trusted output.</p>"
    )
    optimizer_copy = (
        "Details-page optimizer использует server-owned source scope выбранного кейса. Python классифицирует risk, выбирает mode или recipe, может применить узкий deterministic recipe patch, иначе просит LLM собрать draft, затем валидирует read-only scope, table set, filters, joins, projection shape, result shape и recipe-specific invariants перед доверием SQL draft."
        if llm_enabled
        else "Details-page optimizer использует server-owned source scope выбранного кейса. Python классифицирует risk, выбирает mode или recipe, может применить узкий deterministic recipe patch, затем валидирует read-only scope, table set, filters, joins, projection shape, result shape и recipe-specific invariants перед доверием SQL draft."
    )
    auto_report_answer = (
        "Чтобы не запускать массовую LLM-генерацию и не создавать trusted-looking output без выбранного кейса. Генерация отчета остается явным действием пользователя."
        if llm_enabled
        else "Чтобы не создавать trusted-looking output без выбранного кейса. Генерация отчета остается явным действием пользователя."
    )
    return f"""
<section class="panel docs-panel help-panel" aria-label="Query Doctor help">
<h1>Справка</h1>
<div class="report-body help-body">
<p class="help-lede">Query Doctor - local-first Big Data query diagnostics tool, сфокусированный сегодня на Apache Impala production triage для operators. Он ранжирует подозрительные Recent queries, собирает bounded profile context, выводит deterministic evidence, опционально обогащает его safe metadata и runtime context и генерирует validated raw-free reports. Реализованный production engine сейчас Apache Impala.</p>

<nav class="help-card-grid" aria-label="Help shortcuts">
<a class="help-card" href="/"><span>Диагностика</span><strong>Разобрать Recent queries или один Known Query ID.</strong></a>
<a class="help-card" href="/#recent-results"><span>Результаты</span><strong>Смотреть priority filters, findings, metadata и stats signals.</strong></a>
<a class="help-card" href="#details-actions"><span>Детали</span><strong>Начать с Recommended changes, затем раскрывать evidence.</strong></a>
<a class="help-card" href="/trino/compact-diagnosis"><span>Trino compact</span><strong>Рендерит direct или packaged raw-free boundary JSON, не product support.</strong></a>
<a class="help-card" href="#safety"><span>Безопасность</span><strong>Что browser output намеренно скрывает.</strong></a>
</nav>

<h2>На этой странице</h2>
<ul class="help-toc">
<li><a href="#quick-start">Быстрый старт</a></li>
<li><a href="#workflows">Рабочие режимы</a></li>
<li><a href="#results-table">Таблица результатов</a></li>
<li><a href="#details-actions">{actions_label}</a></li>
<li><a href="#metadata">Метаданные</a></li>
<li><a href="#safety">Граница безопасности</a></li>
<li><a href="#github-docs">Документация GitHub</a></li>
<li><a href="#common-questions">Частые вопросы</a></li>
</ul>

<section id="quick-start" class="help-section-block">
<h2>Быстрый старт</h2>
<ol class="help-step-list">
<li><a href="/">Откройте Diagnose</a> и выберите <strong>Finished queries</strong>, <strong>Running now</strong> или <strong>One Query ID</strong> в первом переключателе.</li>
<li>Для обычного batch triage используйте <strong>Finished queries</strong>. <strong>Running now</strong> оставляйте для live snapshot с меньшей уверенностью.</li>
<li>Переключитесь на <strong>Known Query ID</strong>, если у вас уже есть один query ID. Фильтры Recent-query в этом режиме скрыты.</li>
<li>Откройте строку результата в той же вкладке и начните с <strong>Recommended changes</strong>. <strong>Diagnostics and evidence</strong> раскрывайте, когда нужна техническая база.</li>
<li>{selected_action_line}</li>
</ol>
</section>

<div class="help-topic-stack">
<details id="workflows" class="help-topic" open>
<summary><span>Рабочие режимы</span><small>Recent queries, Running now, Known Query ID</small></summary>
<div class="help-topic-body">
<p>Flagship workflow для operator triage - <strong>Recent queries</strong>. <strong>Known Query ID</strong> нужен, когда уже известен один query ID и batch discovery не требуется.</p>
<h3>Recent queries</h3>
<p>Recent queries читает summaries из выбранного источника, применяет фильтры, собирает bounded profiles, запускает детерминированный analysis и показывает action-oriented result filters. {web_scan_boundary}</p>
<ul>
<li>Сначала проверьте <strong>Source cluster</strong>. Credentials и endpoints остаются в local config.</li>
<li>Первый переключатель выбирает <strong>Finished queries</strong>, <strong>Running now</strong> или <strong>One Query ID</strong>. Finished queries остается основным triage path.</li>
<li>Для <strong>Finished queries</strong> задайте <strong>Scan date</strong> и <strong>Scan Hour</strong>. Оставьте <strong>Minimum duration</strong> пустым, чтобы включить длинные запросы и repeated short workload patterns; задайте значение, чтобы сузить скан до долгих запросов.</li>
<li>Runtime context собирается автоматически, когда выбранный source это поддерживает.</li>
<li>Фильтр Results показывает все доступные срезы в одной панели: <strong>Needs attention</strong>, <strong>Worth reviewing</strong>, repeated workloads, rewrite opportunities и stats candidates.</li>
<li><strong>Only queries with spills</strong> - display filter по уже проанализированным результатам.</li>
</ul>
<h3>Running now</h3>
<p>Running now использует такую же форму результатов и Details, но сканирует только running queries на момент запуска. Профили могут быть неполными, поэтому уверенность ниже, чем для completed-query analysis.</p>
<h3>Known Query ID</h3>
<p>Known Query ID анализирует один явный query ID. Используйте общий Cluster selector, введите Query ID и запустите analysis. {known_query_boundary}</p>
</div>
</details>

<details id="results-table" class="help-topic">
<summary><span>Таблица результатов</span><small>Фильтры, колонки и triage wording</small></summary>
<div class="help-topic-body">
<p>Таблица - triage surface. Перед production changes открывайте строку в Details.</p>
<h3>Колонки и фильтры</h3>
<ul>
<li>Панель фильтров показывает counts для доступных result views, а компактная пометка <strong>Scanned</strong> показывает объем просмотренных summaries.</li>
<li><strong>Scan context</strong> после таблицы объясняет coverage, notes и workload signals для текущего result set. Critical scan warnings остаются видимыми над таблицей.</li>
<li><strong>Rank</strong> - порядок внутри текущей группы, не root-cause verdict.</li>
<li><strong>Query ID</strong> открывает details page выбранного кейса.</li>
<li><strong>Priority</strong> объединяет word label и deterministic analyzer score.</li>
<li><strong>Rewrite opportunities</strong> и <strong>Stats to check</strong> показывают только поддержанные кандидаты для проверки.</li>
</ul>
</div>
</details>

<details id="details-actions" class="help-topic">
<summary><span>{actions_label}</span><small>Рекомендации, диагностика, отчеты, optimizer</small></summary>
<div class="help-topic-body">
<p>Details - browser-safe summary для одного analyzed query. <strong>Recommended changes</strong> сначала показывает, что изменить и как проверить результат, затем где смотреть и почему deterministic facts поддерживают этот путь. <strong>Diagnostics and evidence</strong> держит pipeline state, findings, runtime, metadata и technical signals в collapsed виде.</p>
{action_copy}
<h3>Validated reports</h3>
{report_copy}
<p>Report writer читает deterministic facts, Python-owned report contract digest, differentiators и recommendation candidates. Он не должен выводить из raw profile text или raw SQL.</p>
<h3>Details-page {optimizer_label}</h3>
<p>{optimizer_copy}</p><p>Если validation fails, Query Doctor может показать trusted recommendations-only или no-rewrite guidance вместо unsafe draft.</p>
</div>
</details>

<details id="metadata" class="help-topic">
<summary><span>Метаданные</span><small>Bounded read-only table facts</small></summary>
<div class="help-topic-body">
<p>Metadata collection явная, bounded, read-only и allowlisted. Partial или unavailable metadata - нормальное degraded state.</p>
<h3>Allowed metadata summaries</h3>
<ul><li>Table definition summary</li><li>Table statistics summary</li><li>Column statistics summary</li></ul>
<p>Query Doctor не запускает user queries, maintenance statements, metadata cache updates, schema changes или data-changing statements для metadata collection.</p>
</div>
</details>

<details id="safety" class="help-topic">
<summary><span>Граница безопасности</span><small>Что browser output показывает и скрывает</small></summary>
<div class="help-topic-body">
<p>Browser UI намеренно скрывает raw query text, raw profile text, raw metadata output, filesystem locations, case directory details, process output, secrets, environment secret values, runtime internals и raw evidence links.</p>
<p>Safe browser output - это summarized deterministic facts, statuses, validated reports, trusted optimizer outcomes и bounded limitations.</p>
</div>
</details>

<details id="github-docs" class="help-topic">
<summary><span>Документация GitHub</span><small>Поддерживаемые внешние docs</small></summary>
<div class="help-topic-body">
<p>Эта страница остается короткой и task-oriented. Полная documentation живет в repository на GitHub:</p>
<ul class="help-link-list">
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/README.md" target="_blank" rel="noopener noreferrer">Project README</a></li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/README.md" target="_blank" rel="noopener noreferrer">Documentation index</a></li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/security-model.md" target="_blank" rel="noopener noreferrer">Security model</a></li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/safety-contract.md" target="_blank" rel="noopener noreferrer">Safety contract</a></li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/roadmap.md" target="_blank" rel="noopener noreferrer">Roadmap</a></li>
<li><a href="https://github.com/alexandrefimov/Query-Doctor/blob/main/docs/DEMO.md" target="_blank" rel="noopener noreferrer">Synthetic demo docs</a></li>
</ul>
</div>
</details>

<details id="common-questions" class="help-topic">
<summary><span>Частые вопросы</span><small>Безопасность, metadata, reports и scope</small></summary>
<div class="help-topic-body">
<h3>Почему не видно query SQL?</h3><p>Raw query text может содержать sensitive business logic, table names и literals. Query Doctor показывает safe summaries и deterministic findings.</p>
<h3>Почему не видно полный profile?</h3><p>Full profiles могут быть большими и sensitive. UI показывает analyzer-owned facts и bounded status summaries.</p>
<h3>Почему metadata partial или skipped?</h3><p>Metadata collection bounded. Ее можно отключить, источник может быть недоступен, сбор может ограничиться top cases или остановиться по safety limits. Profile-based findings остаются usable.</p>
<h3>Почему Recent queries не генерирует reports автоматически?</h3><p>{auto_report_answer}</p>
<h3>Может ли Query Doctor выполнить optimized SQL?</h3><p>Нет. Optimizer actions могут создать trusted drafts или recommendations, но Query Doctor никогда не выполняет generated SQL.</p>
<h3>Означает ли stats gap, что stats вызвали slowdown?</h3><p>Нет. Это statistics update candidate только когда metadata gaps, estimate mismatch и planning-sensitive runtime symptoms сходятся. Подтверждение требует EXPLAIN comparison и comparable rerun.</p>
<h3>Доказывает ли runtime metrics context root cause?</h3><p>Обычно нет. Runtime metrics - bounded context. Они становятся сильнее только при correlation с deterministic profile evidence.</p>
<h3>Future scope</h3>
<h3>Может ли Query Doctor поддерживать Trino, Spark SQL, StarRocks, Doris, ClickHouse, Dremio или другой Big Data SQL engine?</h3>
<p>Пока нет. Future engine work ограничен actively developed Big Data SQL, MPP analytical и lakehouse runtimes, а не generic OLTP databases. Каждый engine требует safe read-only collection contract, metadata allowlist, parser/profile support, browser safety tests и report validator coverage.</p>
<h3>Имеет ли значение storage backend?</h3>
<p>Да, но это отдельное измерение от query engine. Query Doctor может сохранять bounded storage-family context, например HDFS или object-store, когда metadata дает безопасную location scheme. Он не показывает table locations или object URIs, а object-store remote reads не трактуются как HDFS locality failures. Future table-layout context может поддерживать candidates вроде small-file risk или planning pressure, но storage context сам по себе не доказывает root cause.</p>
</div>
</details>
</div>
</section>
""".strip()
