"""Recent query scan rendering helpers for the local Query Doctor UI."""

from __future__ import annotations

from query_doctor.web.ui.recent_scan_details import (
    SafeHtml,
    batch_case_display_report_status,
    batch_report_status,
    badge_html,
    case_has_failure,
    compact_cell,
    display_score,
    escape_value,
    explain_score_reason,
    has_metadata_aggregate_facts,
    metadata_fact_limitations,
    metadata_rows,
    metadata_score_reasons,
    metadata_statement_counts_summary,
    numeric_value,
    reason_cell,
    render_batch_case_detail,
    render_batch_case_report_action,
    render_case_status_summary,
    render_metadata_fact_table_row,
    render_metadata_fact_table_row_view,
    render_metadata_facts_body,
    render_metadata_facts_section,
    render_metadata_facts_view,
    render_runtime_signals,
    render_recent_scan_case_detail_view,
    render_score_reason_card,
    render_score_reason_card_view,
    render_score_reason_explanations,
    render_score_reason_explanations_view,
    render_technical_details,
    report_badge,
    score_badge,
    status_badge,
)
from query_doctor.web.ui.recent_scan_form import (
    form_or_config_bool,
    form_or_config_value,
    read_local_config_values,
    render_batch_number_field,
    render_batch_run_panel,
    render_batch_text_field,
)
from query_doctor.web.ui.recent_scan_results import (
    batch_progress_percent,
    batch_case_details_link,
    batch_case_id,
    case_detail,
    discovery_detail,
    metadata_detail,
    numeric_count,
    progress_step,
    read_batch_progress_events,
    render_batch_card,
    render_batch_case_row,
    render_batch_empty_note,
    render_batch_progress_panel,
    render_batch_scope_note,
    render_batch_summary,
    summarize_batch_progress,
)
