"""Default LLM report contract headings and prompt policy.

The legacy module-level constants intentionally expose the Russian contract for
existing validators and tests. New language-aware code should use
``get_report_language_contract`` instead.
"""

from query_doctor.report.language_contract import (
    REPORT_LANGUAGE_CONTRACTS,
    RU_REPORT_CONTRACT,
    SUPPORTED_REPORT_LANGUAGES,
    ReportLanguageContract,
    get_report_language_contract,
)

__all__ = [
    "REPORT_LANGUAGE_CONTRACTS",
    "RU_REPORT_CONTRACT",
    "SUPPORTED_REPORT_LANGUAGES",
    "ReportLanguageContract",
    "get_report_language_contract",
    "REPORT_TITLE_HEADING",
    "REPORT_SYSTEM_PROMPT",
    "SHORT_SUMMARY_HEADING",
    "RECOMMENDATIONS_HEADING",
    "DETAILED_REPORT_HEADING",
    "ANALYZER_FACTS_HEADING",
    "TABLE_METADATA_CONTEXT_HEADING",
    "CM_TIMESERIES_CONTEXT_HEADING",
    "CM_METRICS_FACTS_HEADING",
    "CM_METRICS_CORRELATION_HEADING",
    "CLUSTER_RUNTIME_CONTEXT_HEADING",
    "EVIDENCE_SAFE_PROBLEMS_HEADING",
    "EVIDENCE_HEADING",
    "AMPLIFIERS_HEADING",
    "NOT_SUPPORTED_HEADING",
    "NEXT_CHECKS_HEADING",
    "REQUIRED_REPORT_SECTIONS",
    "ROOT_CAUSE_HEADING_REWRITE",
    "DETAIL_HEADING_REWRITE",
    "USER_READ_ONLY_HEADING",
    "USER_ADMIN_PACKAGE_HEADING",
    "USER_VALIDATION_HEADING",
    "USER_VERIFY_HEADING",
    "USER_HEADING_REWRITE",
]


REPORT_TITLE_HEADING = RU_REPORT_CONTRACT.title_heading
REPORT_SYSTEM_PROMPT = RU_REPORT_CONTRACT.system_prompt
SHORT_SUMMARY_HEADING = RU_REPORT_CONTRACT.short_summary_heading
RECOMMENDATIONS_HEADING = RU_REPORT_CONTRACT.recommendations_heading
DETAILED_REPORT_HEADING = RU_REPORT_CONTRACT.detailed_report_heading
ANALYZER_FACTS_HEADING = RU_REPORT_CONTRACT.analyzer_facts_heading
TABLE_METADATA_CONTEXT_HEADING = "## Table Metadata Context"
CM_TIMESERIES_CONTEXT_HEADING = "## CM Time-Series Context"
CM_METRICS_FACTS_HEADING = "## CM Metrics Facts"
CM_METRICS_CORRELATION_HEADING = "## CM Metrics Correlation"
CLUSTER_RUNTIME_CONTEXT_HEADING = "## Cluster Runtime Context"
EVIDENCE_SAFE_PROBLEMS_HEADING = RU_REPORT_CONTRACT.evidence_safe_problems_heading
EVIDENCE_HEADING = RU_REPORT_CONTRACT.evidence_heading
AMPLIFIERS_HEADING = RU_REPORT_CONTRACT.amplifiers_heading
NOT_SUPPORTED_HEADING = RU_REPORT_CONTRACT.not_supported_heading
NEXT_CHECKS_HEADING = RU_REPORT_CONTRACT.next_checks_heading
REQUIRED_REPORT_SECTIONS = RU_REPORT_CONTRACT.required_sections
ROOT_CAUSE_HEADING_REWRITE = RU_REPORT_CONTRACT.root_cause_heading_rewrite
DETAIL_HEADING_REWRITE = RU_REPORT_CONTRACT.detail_heading_rewrite
USER_READ_ONLY_HEADING = RU_REPORT_CONTRACT.user_read_only_heading
USER_ADMIN_PACKAGE_HEADING = RU_REPORT_CONTRACT.user_admin_package_heading
USER_VALIDATION_HEADING = RU_REPORT_CONTRACT.user_validation_heading
USER_VERIFY_HEADING = RU_REPORT_CONTRACT.user_verify_heading
USER_HEADING_REWRITE = RU_REPORT_CONTRACT.user_heading_rewrite
